### ISSUE TITLE
Crash before Nero

### ISSUE THREAD

**Issue by fitqt** [Judisch/FastPraetorium#1]

**Comment by fitqt** [comment]
`2021-11-17 19:36:16.083 +01:00 [ERR] [FastPraetorium] UiBuilder OnBuildUi caught exception
System.InvalidOperationException: Static pointer for Framework::Instance is null. Did you forget to call Resolver.Initialize?
   at FFXIVClientStructs.FFXIV.Client.System.Framework.Framework.Instance() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.Generators\FFXIVClientStructs.Generators.StaticAddressGenerator.StaticAddressGenerator\FFXIVClientStructs.FFXIV.Client.System.Framework.Framework.StaticAddresses.generated.cs:line 11
   at FastPraetorium.FastPraetorium.ChangeCutsceneAudioLanguage(UInt32 language) in C:\Users\user\Documents\Plugins_building\FastPraetorium\FastPraetorium.cs:line 85
   at FastPraetorium.FastPraetorium.OnTargetChanged(UInt32 id) in C:\Users\user\Documents\Plugins_building\FastPraetorium\FastPraetorium.cs:line 52
   at FastPraetorium.FastPraetorium.CheckTargetChanged() in C:\Users\user\Documents\Plugins_building\FastPraetorium\FastPraetorium.cs:line 36
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 287`
